// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    APlayer: typeof import('./src/components/aPlayer/index.vue')['default']
    Controller: typeof import('./src/components/aPlayer/controller.vue')['default']
    ControllerProgress: typeof import('./src/components/aPlayer/controllerProgress.vue')['default']
    ControllerVolume: typeof import('./src/components/aPlayer/controllerVolume.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thumbnail: typeof import('./src/components/aPlayer/thumbnail.vue')['default']
  }
}

export {}
